### ISSUE TITLE
How to keep camera pose of reference images fixed while running mapper with query images?

### ISSUE THREAD

**Issue by patelajaychh** [tsattler/visloc_pseudo_gt_limitations#2]
#1 Thanks for quick response!

According to reply to #1 , `--fix_existing_images`  is set to `True` while creating poses for query images.

Passage from Paper 
```
First, we reconstruct the scene with SfM using only the training images. Next, we continue the reconstruction process with the test images while keeping the training
camera poses fixed.
```

According to this passage, doesn't this mean that `--fix_existing_images` should be set to `False`? or am I missing something?

**Comment by tsattler** [comment]
The `--fix_existing_images` parameters fixes the poses of images contained in a 3D model loaded from disk. Setting it to `True` is thus what you want to do for the training poses.
