### ISSUE TITLE
Test results in paper

### ISSUE THREAD

**Issue by SeanGuo063** [tsattler/visloc_pseudo_gt_limitations#6]
Very impressive work! I notice that the test result of DSAC* on dslam gt in is paper is much much higher than the original DSAC* paper. So, what is the difference of the method between these two version? What may cause the difference?

**Comment by tsattler** [comment]
@ebrach Can you answer this one?

**Comment by ebrach** [comment]
Hi Sean,

I'm not sure what numbers you are referring to. The RGB-D version of DSAC* performs identical (up to 0.1%) across the two papers on 7Scenes. The RGB version performs slightly worse than in the original paper - for the reasons explained in Sec. A.4.

Best,
Eric
